Support components
discordcf/discordcf pull request #14
Opened 2022-06-05 22:12 UTC by Inrixia

Opening this PR to begin discussion on this feature to add support for components. This is mostly done though re https://github.com/alvgaona/cloudflare-discord-bot/pull/13#pullrequestreview-996031451 and https://github.com/alvgaona/cloudflare-discord-bot/pull/12

I'll need to update formatting first. I intend to setup a eslinf config that closely mirrors the original files format and use that since I have vs setup to properly format/fix files on saving.

2022-06-05 22:14 UTC, Inrixia commented
I also need to move types into the proper file and I want to check if there is a better source for the discord api types (like discord.js) as they are very incomplete

2022-06-09 12:33 UTC, Inrixia commented
> > I also need to move types into the proper file and I want to check if there is a better source for the discord api types (like discord.js) as they are very incomplete
> 
> @Inrixia all the types should be in here: https://discord.com/developers/docs

Yep see https://github.com/alvgaona/cloudflare-discord-bot/issues/16 I've already made good headway on switching to the official api types package, it's all uncommitted on this branch

2022-06-09 12:47 UTC, alvgaona commented
> > > I also need to move types into the proper file and I want to check if there is a better source for the discord api types (like discord.js) as they are very incomplete
> > 
> > 
> > @Inrixia all the types should be in here: https://discord.com/developers/docs
> 
> Yep see #16 I've already made good headway on switching to the official api types package, it's all uncommitted on this branch

Excellent. I've assigned that issue to you. Feel free to work it out.

2022-06-10 02:50 UTC, Inrixia commented
This has now been updated to be upstream from the latest merges to main on this repo.

This PR does two main things, adds a components field for people to add handlers for and changes behind the scenes handling for commands to use a dict for easy lookup instead of an array (which had to be searched every request).

2022-07-04 22:33 UTC, alvgaona commented
Hi, @Inrixia my apologies for delaying this. I promise this week I'll spend some time on it. I'll get back to you.

2022-07-21 04:50 UTC, Inrixia commented
@alvgaona This branch has tons of fixes including switching to new types mentioned in https://github.com/alvgaona/cloudflare-discord-bot/issues/16 and support for components. I've been updating it as I encounter issues while using it for other projects

2022-07-24 23:59 UTC, alvgaona approved these changes
This is looking pretty neat!

2022-07-24 23:59 UTC, alvgaona commented on src/permissions.ts
> +    console.log(permission, String(permission));
@Inrixia do we want to log this?

2022-07-25 00:08 UTC, Inrixia commented on src/permissions.ts
> +    console.log(permission, String(permission));
Oops, that's leftover from me testing. I'll remove it

2022-07-25 00:22 UTC, alvgaona commented
@Inrixia feel free to merge it if you think this PR's done.

2022-07-25 00:48 UTC, Inrixia commented
This pr has some breaking changes afik, so maybe just double check @alvgaona

2022-07-25 00:53 UTC, alvgaona commented
> This pr has some breaking changes afik, so maybe just double check @alvgaona

Let me run a smoke test then.

2022-08-16 02:57 UTC, alvgaona requested changes
Hi @Inrixia, sorry it took me a while to look at this in depth. 

I feel like I need an example from a client's point of view. This PR touches the core of the library and we need to look at this from that point of view as well in this PR. I've tried to set up my own bot off of this PR but had some doubts about it, seems like there are missing types that we could export in order to properly set up commands for instance when writing a bot.

Do you think you could set up a "hello world" bot? It'd be very useful as we could harness that piece of code to set up testing.

2022-08-16 02:57 UTC, alvgaona commented on src/handler.ts
> +export type Command<DataType extends InteractionDataType | void = void> = [
@Inrixia how do we create a command out of this type? Do you have an example?

2022-08-16 02:57 UTC, alvgaona commented on src/handler.ts
> +  components?: Record<string, ComponentInteractionHandler>;
Any example of how to use the components in this case?

2022-08-16 02:57 UTC, alvgaona commented on src/interaction.ts
> +export type InteractionResponse = Promise<APIInteractionResponse> | APIInteractionResponse;
How is this type used in terms of a client of this library?

2022-08-16 03:08 UTC, Inrixia commented
Hey no problem on the delay. Will give this a proper look over when I get time but for now you can see an example bot using this here: https://github.com/Inrixia/LostMokoko

I'll join the discord server so feel free to message me questions there or here.

2022-08-19 23:59 UTC, Inrixia commented on src/handler.ts
> +export type Command<DataType extends InteractionDataType | void = void> = [
https://github.com/Inrixia/LostMokoko/blob/deb098244c4b5868632b1ad2f879a9941933a957/src/reactMentions.ts#L21

2022-08-20 00:12 UTC, Inrixia commented on src/handler.ts
> +  components?: Record<string, ComponentInteractionHandler>;
I had a test command which returned a message with a button a user could click in this commit https://github.com/Inrixia/LostMokoko/blob/5065d55612ec136ef7360646da17be965259cd6f/src/hello.ts

Note how the `custom_id` is the same in the command definition
https://github.com/Inrixia/LostMokoko/blob/5065d55612ec136ef7360646da17be965259cd6f/src/hello.ts#L38-L44

and the component definition
https://github.com/Inrixia/LostMokoko/blob/5065d55612ec136ef7360646da17be965259cd6f/src/hello.ts#L51-L62

2022-08-20 00:19 UTC, Inrixia commented on src/interaction.ts
> +export type InteractionResponse = Promise<APIInteractionResponse> | APIInteractionResponse;
Assuming you are referring to `InteractionResponse` that type is the expected type any interaction handler will return.

For example this returned object conforms to the `InteractionResponse` type https://github.com/Inrixia/LostMokoko/blob/deb098244c4b5868632b1ad2f879a9941933a957/src/reactMentions.ts#L101-L106

Its specifically this response type
https://github.com/discordjs/discord-api-types/blob/35b17dcbf894b8edf0edbc4c831932192266461e/payloads/v10/_interactions/responses.ts#L48-L51

2022-09-27 10:20 UTC, Inrixia commented
@alvgaona Have a look at my responses and the example repo. Can discuss further if you like

2022-10-24 02:32 UTC, alvgaona requested changes
@Inrixia finally the review. Sorry for the long wait, we're definitely improving this! Thanks a lot.

2022-10-24 02:32 UTC, alvgaona commented on package.json
> +		"discord-api-types": "^0.33.5",
Let's bump this version up a little bit, to the latest, if possible.

2022-10-24 02:32 UTC, alvgaona commented on src/interaction.ts
> +  APIContextMenuInteractionData as MenuInteractionData,
Can you remove the `as`? I know the names are a bit longer but it's much clear.

2022-10-24 02:32 UTC, alvgaona commented on src/interaction.ts
> +  ContextMenu,
Same here. Let's use `discord-api-types` names directly.

2022-10-24 02:32 UTC, alvgaona commented on src/setup.ts
> +const deleteExistingCommands = async (applicationId: string, applicationSecret: string, guildId?: string): Promise<void> => {
```suggestion
const deleteExistingCommands = async (applicationId: string, botToken: string, guildId?: string): Promise<void> => {
```

As it's not anymore the `CLIENT_SECRET` used in here, we're using the Bot's token.

2022-10-24 02:32 UTC, alvgaona commented on src/setup.ts
> +    headers: { "Content-Type": "application/json", Authorization: `Bot ${applicationSecret}` },
```suggestion
    headers: { "Content-Type": "application/json", Authorization: `Bot ${token}` },
```

2022-10-24 02:32 UTC, alvgaona commented on src/setup.ts
> +        headers: { Authorization: `Bot ${applicationSecret}` },
```suggestion
        headers: { Authorization: `Bot ${token}` },
```

2022-10-24 02:32 UTC, alvgaona commented on src/setup.ts
> +const createCommands = async ({ applicationId, guildId, commands }: createCommandsArgs, applicationSecret: string): Promise<Response> => {
```suggestion
const createCommands = async ({ applicationId, guildId, commands }: createCommandsArgs, token: string): Promise<Response> => {
```

2022-10-24 02:32 UTC, alvgaona commented on src/setup.ts
> +        headers: { "Content-Type": "application/json", Authorization: `Bot ${applicationSecret}` },
```suggestion
        headers: { "Content-Type": "application/json", Authorization: `Bot ${token}` },
```

2022-10-24 02:32 UTC, alvgaona commented on src/handler.ts
>    applicationSecret: string;
```suggestion
  botToken: string;
```

2022-10-24 14:16 UTC, Inrixia commented
Had a quick look at your comments. All looks good will sort this tomorrow

2022-10-25 08:26 UTC, Inrixia commented
Surprise, more commits.

I went ahead and did some tests and realized that this library was using Node.js libraries *naughty* for encryption so I have replaced them allowing for running code directly on workers without the need for painful transpiling.

I have also exported all the `discord-api-types` directly from the package so people won't need to go looking for them or look to install the package themselves for them.

Finally I added a proper example both in the updated readme and in the new examples folder.

Please take a look and lemme know if you need any other changes before merging

2022-10-25 21:45 UTC, alvgaona requested changes
Nice changes @Inrixia! Left a few comments, nothing to big and a few questions for you.

Regarding the example: can we move away the example to a different repository? If you'd like to have the example linked to this repo we could use `git submodules`. 

I have created this https://github.com/discordcf/hello-bot to make it public once we make a new release of the framework.

2022-10-25 21:45 UTC, alvgaona commented on examples/hello/.gitignore
> +wrangler.toml
The file needs an empty line at the EOF.

2022-10-25 21:45 UTC, alvgaona commented on examples/hello/package.json
> +    "cloudflare-discord-bot": "../../",
We'll change the name of the library to something nicer (follow-up PR).

2022-10-25 21:45 UTC, alvgaona commented on examples/hello/src/hug.ts
> +    if (userId === undefined) throw new Error(`User is undefined`);
I think we can do `if (!userId)` to be a little broader. Like `""`, `null`, `undefined` would work as a falsy value.

2022-10-25 21:45 UTC, alvgaona commented on src/setup.ts
> +  return RouteBases.api + Routes.applicationCommands(applicationId);
```suggestion
  if (guildId) return RouteBases.api + Routes.applicationGuildCommands(applicationId, guildId);
  return RouteBases.api + Routes.applicationCommands(applicationId);
```

2022-10-25 21:45 UTC, alvgaona commented on src/setup.ts
> +  return RouteBases.api + Routes.applicationCommands(applicationId);
Same idea as above.

2022-10-25 21:45 UTC, alvgaona commented on src/interaction.ts
> +  ContextMenu,
I think we need to replace these names as they don't exist anymore in the file.

2022-10-25 21:45 UTC, alvgaona commented on src/interaction.ts
> +  const encoder = new TextEncoder();
Neat!

2022-10-25 21:45 UTC, alvgaona commented on src/handler.ts
> +
What do you think of creating a `Component` type similar to this?

```typescript
type Component = [
 string,
 ComponentInteractionHandler
]
```

2022-10-25 21:45 UTC, alvgaona commented on src/handler.ts
> +  commands: Command<any>[];
Should we change `any` to a more restrictive type? WDYT?

2022-10-25 21:53 UTC, Inrixia commented
@alvgaona great comments. Will update when I get home

2022-10-27 05:47 UTC, Inrixia commented on src/handler.ts
> +  commands: Command<any>[];
I always avoid using `any` where possible but in this case narrowing is not possible as different command signatures are incompatible with each other.

2022-10-27 05:50 UTC, Inrixia commented on src/handler.ts
> +
There is no point as `ComponentInteractionHandler` is already exported to the user. Also the type you specified here is wrong, Components use a dict not an array.

2022-10-27 05:51 UTC, Inrixia commented on src/interaction.ts
> +  ContextMenu,
Both names are still used?
`ChatInput` is for API**ChatInput**ApplicationCommandInteractionData
`ContextMenu` is for API**ContextMenu**InteractionData

2022-10-27 05:54 UTC, Inrixia commented on examples/hello/src/hug.ts
> +    if (userId === undefined) throw new Error(`User is undefined`);
This is a bad idea, you always want strict checks. The typings say that you will only get undefined. Not doing strict checks can leave to unexpected behaviour.

2022-10-27 05:54 UTC, Inrixia commented on src/setup.ts
> +  return RouteBases.api + Routes.applicationCommands(applicationId);
See above

2022-10-27 06:01 UTC, Inrixia commented
> Regarding the example: can we move away the example to a different repository? If you'd like to have the example linked to this repo we could use `git submodules`. Additionally, we could automate the update every time a push event is emitted from the main branch in that repo (but this is an optimization).

This is over engineering, having multiple repos for examples etc is more difficult all round especially for users to find them (most of the time they won't) and makes maintaining them harder. Also the fact that you suggest adding automation to update the main repo when changes are pushed from the secondary is a pretty clear indicator that it belongs in the main repo.

Speaking from experience of converting a major project to submodules in a github org (at least 8 repos + 2 helper repos and 1 "main" repo) and back again submodules look nice but can be a nightmare in practise, they have their use but this is definitely not it and I personally would advocate against using them as monorepos are much much easier to deal with.

2022-10-27 17:52 UTC, alvgaona requested changes
Just reopened a conversation. Let's add that, I'm afraid that for some reason Discord API changes for some reason and breaks us.

2022-10-27 17:52 UTC, alvgaona commented on src/interaction.ts
> +  ContextMenu,
Yes, my bad! Don't know what I was thinking.

2022-10-27 17:55 UTC, alvgaona commented
> > Regarding the example: can we move away the example to a different repository? If you'd like to have the example linked to this repo we could use `git submodules`. Additionally, we could automate the update every time a push event is emitted from the main branch in that repo (but this is an optimization).
> 
> This is over engineering, having multiple repos for examples etc is more difficult all round especially for users to find them (most of the time they won't) and makes maintaining them harder. Also the fact that you suggest adding automation to update the main repo when changes are pushed from the secondary is a pretty clear indicator that it belongs in the main repo.
> 
> Speaking from experience of converting a major project to submodules in a github org (at least 8 repos + 2 helper repos and 1 "main" repo) and back again submodules look nice but can be a nightmare in practise, they have their use but this is definitely not it and I personally would advocate against using them as monorepos are much much easier to deal with.

@Inrixia I'm not suggesting we use a repo for each example bot. At the moment this is the only example we've got but we could do a monorepo for the examples, I'm in favor of doing that. I would prefer we keep this core repo as lean as possible, and just link to the examples repo in the documentation. If we don't want to do submodules, I'm fine with it; although, I do insist we keep the examples in a repo named `discordcf/example-bots` or sth.

2022-10-31 00:01 UTC, Inrixia commented
@alvgaona If we don't have the examples embedded in the repo then submodules is a good intermediary as at least on github it links nicely on the web ui.

2022-10-31 00:03 UTC, Inrixia commented
Also you should rename all the example repos to be prefixed with `examples-` or some other tag so it's easier to find them, currently it's not obvious at all what they are.

2022-10-31 00:58 UTC, alvgaona approved these changes

2022-10-31 01:01 UTC, merged